name: Flutter Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  
          
      - name: Check Flutter
        run: flutter --version
        
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
